### ISSUE TITLE
asking for password when quiting.

### ISSUE THREAD

**Issue by Pietro222222** [brejela/steelbox#2]
instead of asking for the password *before* loading the password manager, it asks for it when you quit.

https://user-images.githubusercontent.com/62407732/147773591-331b2367-dedf-4e0c-bf3c-83dde22b6a17.mp4

**Comment by brejela** [comment]
## **· Working as intended.**
**You must insert your password to unlock the file, and lock it back with a password, that's just how GnuPG's symmetric encryption works.**
That is done so that the master key isn't stored anywhere in the system.
